"""fix missing column in game

Revision ID: 5c53cdd3f6d2
Revises: f8f76243680c
Create Date: 2018-08-28 16:29:00.897160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c53cdd3f6d2'
down_revision = 'f8f76243680c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('bet_pool', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('current_bet', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'current_bet')
    op.drop_column('game', 'bet_pool')
    # ### end Alembic commands ###
