"""cards stored in database 2

Revision ID: bbd45f8c5510
Revises: 9c0aed2daa9e
Create Date: 2018-08-30 18:24:30.123929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd45f8c5510'
down_revision = '9c0aed2daa9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'card_set', ['deck_id'], ['id'])
    op.add_column('game', sa.Column('dealer_hand_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('player_hand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'card_set', ['player_hand_id'], ['id'])
    op.create_foreign_key(None, 'game', 'card_set', ['dealer_hand_id'], ['id'])
    op.create_foreign_key(None, 'game', 'card_set', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'player_hand_id')
    op.drop_column('game', 'deck_id')
    op.drop_column('game', 'dealer_hand_id')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'deck_id')
    # ### end Alembic commands ###
