"""Test 2

Revision ID: bd9afc1745b3
Revises: bbd45f8c5510
Create Date: 2018-08-30 19:19:41.396322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9afc1745b3'
down_revision = 'bbd45f8c5510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_dealer_hand_id_fkey', 'game', type_='foreignkey')
    op.drop_constraint('game_deck_id_fkey', 'game', type_='foreignkey')
    op.drop_constraint('game_player_hand_id_fkey', 'game', type_='foreignkey')
    op.drop_column('game', 'dealer_hand_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('dealer_hand_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('game_player_hand_id_fkey', 'game', 'card_set', ['player_hand_id'], ['id'])
    op.create_foreign_key('game_deck_id_fkey', 'game', 'card_set', ['deck_id'], ['id'])
    op.create_foreign_key('game_dealer_hand_id_fkey', 'game', 'card_set', ['dealer_hand_id'], ['id'])
    # ### end Alembic commands ###
