"""fix missing column in player

Revision ID: d987f66e94bb
Revises: 5c53cdd3f6d2
Create Date: 2018-08-28 16:33:18.310883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd987f66e94bb'
down_revision = '5c53cdd3f6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'player', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'player_id')
    # ### end Alembic commands ###
